version: '3.7'

services:

  mysql:
    image: mysql:8.0.30
    ports:
      - "9006:3306/tcp"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=stuart
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 5s
      retries: 10
